site_name: COMP423 Course Notes
theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Tutorials:
      - Rust Setup: tutorials/rust-setup.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details